### ISSUE TITLE
Support AWS Profiles

### ISSUE THREAD

**Issue by tblanchard** [newapplesho/aws-sdk-smalltalk#17]
AWS supports use of profiles for authentication.

Profiles are stored in ~/.aws in files config and credentials.  It should be possible to create a service on a given profile.

**Comment by newapplesho** [comment]
AWS allows credentials to be stored in the .aws directory that I think I wantn't support it.
I like using AWSS3Config default or loaded from environment variables.
Because I suppose this sdk using Cloud Service (e.g. Docker, AWS Fargate).

**Comment by newapplesho** [comment]
https://github.com/newapplesho/aws-sdk-smalltalk/pull/18 PR Merged.
