### ISSUE TITLE
change reference http://mc.stfx.eu/Neo to the GitHub version

### ISSUE THREAD

**Issue by SabineMa** [newapplesho/aws-sdk-smalltalk#4]
would help me if you could change
```
 spec
				project: 'NeoJSON'
				with: [ spec
						className: 'ConfigurationOfNeoJSON';
						versionString: #stable;
						repository: 'http://mc.stfx.eu/Neo' ].
```
to
 `https://github.com/svenvc/NeoJSON`
after there is a tagged or stable version (see here: https://github.com/svenvc/NeoJSON/issues/7)

**Comment by SabineMa** [comment]
stable version of NeoJSON is available now

**Comment by newapplesho** [comment]
OK

**Comment by SabineMa** [comment]
could you please also create a tag when you fix it? thank you!

**Comment by newapplesho** [comment]
https://github.com/newapplesho/aws-sdk-smalltalk/releases/tag/v1.10.4

**Comment by SabineMa** [comment]
Thank you!
